#! /bin/bash

echo "Installing nodejs v:14"
sudo apt update
node --version;
if [ $? -ne 0 ]
then
 	curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
	sudo apt install nodejs
	if [ $? -ne 0 ]
	then
		echo "install node js failed"
	else
		nodeversion= $(node --version);
		npmversion= $(npm --version);
		echo "node js installed successfully"
		echo "node version :$nodeversion"
		echo "npm version :$npmversion"
	fi
else
	echo "node js installed already $(node --version)"
fi
